#!/bin/bash
#SUDO                 2022              SERVERHU.EU
cd /data && \
mv /data/.env /root && \
echo "$(grep -v "TOKEN=" /root/.env)" > /data/.env && \
rm -rf /root/.env && \
echo "TOKEN=$1" >> /data/.env